import { describe, expect, it } from "vitest";
import { ANSI_MIN_RATIO, MUTED_MIN_RATIO, ROLES, SELECTION_MIN_VISIBLE_RATIO, TEXT_MIN_RATIO } from "../../src/constants.js";
import { ANSI_SLOT_NAMES } from "../../src/palette/ansi.js";
import { contrastRatio } from "../../src/palette/color.js";
import { loadCuratedThemePacks } from "../../src/palette/theme-pack-library.js";
import { buildThemePack, parseThemePack, parseUserPackManifest } from "../../src/palette/theme-pack.js";
import { readVendoredScheme } from "../../tools/vendor-scheme-library.js";

const ATTRIBUTION = {
  source: "mbadolato/iTerm2-Color-Schemes",
  sourceUrl: "https://github.com/mbadolato/iTerm2-Color-Schemes",
  commit: "752a9c079396cc9939b86e893578ed81e80c140f",
  license: "MIT",
};

describe("buildThemePack", () => {
  it("carries the source scheme's identity and appearance into the manifest", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    expect(pack.manifest.name).toBe("Dracula");
    expect(pack.manifest.family).toBe("Dracula");
    expect(pack.manifest.appearance).toBe("dark");
    expect(pack.manifest.slug).toBe("dracula-dark");
    expect(pack.manifest.attribution).toEqual(ATTRIBUTION);
  });

  it("ships the raw scheme as the windows-terminal payload, apart from a resolved selectionBackground and a repaired ANSI black", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    const wtPayload = pack.payloads["windows-terminal"];
    // Every slot but selectionBackground and black passes through untouched.
    expect(wtPayload).toEqual({ ...scheme, black: wtPayload.black, selectionBackground: wtPayload.selectionBackground });
    // Dracula's own authored selectionBackground measures 1.56 for
    // selection-vs-ground — short of SELECTION_IDEAL_RATIO, and body clears
    // ground by 13.36, comfortably enough room to do better — so CHM-30
    // repairs it rather than shipping it unchanged.
    expect(wtPayload.selectionBackground).not.toBe(scheme.selectionBackground);
    // Dracula's own authored black measures 1.11 against ground — CHM-32's
    // own worked fixture — so it must be repaired rather than shipped
    // nearly invisible.
    expect(wtPayload.black).not.toBe(scheme.black);
    expect(contrastRatio(wtPayload.black, scheme.background)).toBeGreaterThanOrEqual(ANSI_MIN_RATIO);
  });

  it("resolves a role hex table for oh-my-posh and herdr, agreeing on every role but body — herdr's own selection_bg is extra", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    for (const role of ROLES) {
      if (role === "body") continue;
      expect(pack.payloads.herdr[role]).toBe(pack.payloads["oh-my-posh"][role]);
    }
    expect(pack.payloads.herdr.selection_bg).toMatch(/^#[0-9a-f]{6}$/i);
    for (const role of ROLES) {
      expect(pack.payloads["oh-my-posh"][role]).toMatch(/^#[0-9a-f]{6}$/i);
    }
  });

  it("resolves a selection clearing body-on-selection for every bundled pack, and records the achieved selection-vs-ground so a regression is visible", () => {
    // Every bundled pack, generated by tools/build-theme-packs.ts and
    // committed under themes/ — the real 26, not a re-derived copy of the
    // curated table, so this proves what actually ships (CHM-30).
    const packs = loadCuratedThemePacks();
    expect(packs.length).toBeGreaterThan(0);

    for (const pack of packs) {
      const bodyHex = pack.payloads.herdr.body;
      const selectionHex = pack.payloads.herdr.selection_bg;
      const groundHex = pack.payloads.herdr.ground;

      // The hard floor: never traded away, on any of the 26 — see
      // palette/selection.ts's resolveSelectionAndBody.
      expect(contrastRatio(bodyHex, selectionHex)).toBeGreaterThanOrEqual(TEXT_MIN_RATIO);
      // Recorded rather than hidden: every pack reaches at least a visible
      // highlight, even the 10 for which SELECTION_IDEAL_RATIO (2.0) is
      // mathematically unreachable alongside the hard floor above (see
      // CHM-30's own worked proof, e.g. tokyo-night-light's 4.52).
      expect(contrastRatio(selectionHex, groundHex)).toBeGreaterThanOrEqual(SELECTION_MIN_VISIBLE_RATIO);
    }
  });

  it("repairs Solarized Dark's muted, which fails its floor before repair (fixture: 2.11)", () => {
    const scheme = readVendoredScheme("iTerm2 Solarized Dark.json");
    const pack = buildThemePack(scheme, "Solarized", ATTRIBUTION);

    const groundHex = pack.payloads["oh-my-posh"].ground;
    const mutedHex = pack.payloads["oh-my-posh"].muted;
    expect(contrastRatio(mutedHex, groundHex)).toBeGreaterThanOrEqual(MUTED_MIN_RATIO);
  });

  it("clears every text role's floor for every curated family — Gruvbox Dark's accent fails before repair (fixture: 3.48)", () => {
    const scheme = readVendoredScheme("Gruvbox Dark.json");
    const pack = buildThemePack(scheme, "Gruvbox", ATTRIBUTION);

    const groundHex = pack.payloads["oh-my-posh"].ground;
    for (const role of ["body", "accent", "success", "error"] as const) {
      const hex = pack.payloads["oh-my-posh"][role];
      expect(contrastRatio(hex, groundHex)).toBeGreaterThanOrEqual(TEXT_MIN_RATIO);
    }
  });

  it("omits attribution entirely when none is given — a user pack has no upstream to credit", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula");

    expect(pack.manifest.attribution).toBeUndefined();
    expect(Object.hasOwn(pack.manifest, "attribution")).toBe(false);
  });

  it("uses an explicit slug verbatim instead of deriving one from family and appearance", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", undefined, "catppuccin-dark");

    // "catppuccin-dark" is not what toSlug("Dracula", "dark") would produce
    // ("dracula-dark") — proving the explicit slug wins outright, not just
    // as a tiebreak.
    expect(pack.manifest.slug).toBe("catppuccin-dark");
  });

  it("still derives a slug from family and appearance when no explicit slug is given", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    expect(pack.manifest.slug).toBe("dracula-dark");
  });
});

describe("ANSI slot repair (CHM-32)", () => {
  it("clears ANSI_MIN_RATIO for every one of the 16 ANSI slots, in every bundled pack", () => {
    // The real 26 committed under themes/, generated by
    // tools/build-theme-packs.ts — not a re-derived copy — so this proves
    // what actually ships.
    const packs = loadCuratedThemePacks();
    expect(packs.length).toBeGreaterThan(0);

    for (const pack of packs) {
      const scheme = pack.payloads["windows-terminal"];
      for (const slotName of ANSI_SLOT_NAMES) {
        expect(contrastRatio(scheme[slotName], scheme.background)).toBeGreaterThanOrEqual(ANSI_MIN_RATIO);
      }
    }
  });

  // The four bundled packs CHM-32 names by hand: ANSI black shipped
  // byte-identical to the background (contrast 1.00) before this repair —
  // the "black circles in dark mode" bug, Claude Code's own bullet markers
  // drawn in ANSI black.
  const BLACK_AT_ONE_FIXTURES = [
    { slug: "gruvbox-dark", fileName: "Gruvbox Dark.json" },
    { slug: "gruvbox-light", fileName: "Gruvbox Light.json" },
    { slug: "monokai-dark", fileName: "Monokai Classic.json" },
    { slug: "night-owl-dark", fileName: "Night Owl.json" },
  ];

  it.each(BLACK_AT_ONE_FIXTURES)("repairs $slug's ANSI black, shipped byte-identical to its background before CHM-32 (fixture: 1.00)", ({ slug, fileName }) => {
    const originalScheme = readVendoredScheme(fileName);
    expect(contrastRatio(originalScheme.black, originalScheme.background)).toBeCloseTo(1, 2);

    const packs = loadCuratedThemePacks();
    const pack = packs.find((candidate) => candidate.manifest.slug === slug);
    if (!pack) throw new Error(`fixture pack not found: ${slug}`);

    const shippedBlack = pack.payloads["windows-terminal"].black;
    expect(shippedBlack).not.toBe(originalScheme.black);
    expect(contrastRatio(shippedBlack, pack.payloads["windows-terminal"].background)).toBeGreaterThanOrEqual(ANSI_MIN_RATIO);
  });
});

describe("parseThemePack", () => {
  it("round-trips a built pack through JSON", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    const roundTripped = parseThemePack(JSON.parse(JSON.stringify(pack)), "dracula-dark.json");
    expect(roundTripped).toEqual(pack);
  });

  it("names the file when a pack is malformed", () => {
    expect(() => parseThemePack({ manifest: {} }, "broken.json")).toThrow(/broken\.json/);
  });
});

describe("parseUserPackManifest", () => {
  it("parses a user manifest naming a scheme, a family and a declared slug", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const manifest = parseUserPackManifest({ slug: "my-dracula-dark", family: "My Dracula", scheme }, "my-dracula");

    expect(manifest.slug).toBe("my-dracula-dark");
    expect(manifest.family).toBe("My Dracula");
    expect(manifest.scheme).toEqual(scheme);
  });

  it("allows slug and family to both be omitted", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const manifest = parseUserPackManifest({ scheme }, "my-dracula");

    expect(manifest.slug).toBeUndefined();
    expect(manifest.family).toBeUndefined();
  });

  it("names the pack directory when a user manifest is malformed", () => {
    expect(() => parseUserPackManifest({ family: "Broken" }, "broken-pack")).toThrow(/broken-pack/);
  });
});
