import { describe, expect, it } from "vitest";
import { ANSI_MIN_RATIO, MUTED_MIN_RATIO, ROLES, SELECTION_MIN_CHROMA, SELECTION_MIN_VISIBLE_RATIO, TEXT_MIN_RATIO } from "../../src/constants.js";
import { ANSI_SLOT_NAMES } from "../../src/palette/ansi.js";
import { chromaOf, contrastRatio, fromHsl } from "../../src/palette/color.js";
import { loadCuratedThemePacks } from "../../src/palette/theme-pack-library.js";
import { buildThemePack, parseThemePack, parseUserPackManifest } from "../../src/palette/theme-pack.js";
import { readVendoredScheme } from "../../tools/vendor-scheme-library.js";

const ATTRIBUTION = {
  source: "mbadolato/iTerm2-Color-Schemes",
  sourceUrl: "https://github.com/mbadolato/iTerm2-Color-Schemes",
  commit: "752a9c079396cc9939b86e893578ed81e80c140f",
  license: "MIT",
};

describe("buildThemePack", () => {
  it("carries the source scheme's identity and appearance into the manifest", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    expect(pack.manifest.name).toBe("Dracula");
    expect(pack.manifest.family).toBe("Dracula");
    expect(pack.manifest.appearance).toBe("dark");
    expect(pack.manifest.slug).toBe("dracula-dark");
    expect(pack.manifest.attribution).toEqual(ATTRIBUTION);
  });

  it("ships the raw scheme as the windows-terminal payload, apart from a resolved selectionBackground and a repaired ANSI black", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    const wtPayload = pack.payloads["windows-terminal"];
    // Every slot but selectionBackground and black passes through untouched.
    expect(wtPayload).toEqual({ ...scheme, black: wtPayload.black, selectionBackground: wtPayload.selectionBackground });
    // Dracula's own authored selectionBackground measures 1.56 for
    // selection-vs-ground — short of SELECTION_IDEAL_RATIO, and body clears
    // ground by 13.36, comfortably enough room to do better — so CHM-30
    // repairs it rather than shipping it unchanged.
    expect(wtPayload.selectionBackground).not.toBe(scheme.selectionBackground);
    // Dracula's own authored black measures 1.11 against ground — CHM-32's
    // own worked fixture — so it must be repaired rather than shipped
    // nearly invisible.
    expect(wtPayload.black).not.toBe(scheme.black);
    expect(contrastRatio(wtPayload.black, scheme.background)).toBeGreaterThanOrEqual(ANSI_MIN_RATIO);
  });

  it("resolves a role hex table for oh-my-posh and herdr, agreeing on every role but body and muted — herdr's own selection_bg is extra", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    // body and muted are herdr-specific: both are repaired a second time
    // against the selected row's own background (CHM-50's
    // resolveActiveRowAndText), on top of CHM-30's selection-vs-body nudge to
    // body alone — see ThemePackPayloads' own doc comment.
    for (const role of ROLES) {
      if (role === "body" || role === "muted") continue;
      expect(pack.payloads.herdr[role]).toBe(pack.payloads["oh-my-posh"][role]);
    }
    expect(pack.payloads.herdr.selection_bg).toMatch(/^#[0-9a-f]{6}$/i);
    for (const role of ROLES) {
      expect(pack.payloads["oh-my-posh"][role]).toMatch(/^#[0-9a-f]{6}$/i);
    }
  });

  it("resolves a selection clearing body-on-selection for every bundled pack, and records the achieved selection-vs-ground so a regression is visible", () => {
    // Every bundled pack, generated by tools/build-theme-packs.ts and
    // committed under themes/ — the real 26, not a re-derived copy of the
    // curated table, so this proves what actually ships (CHM-30).
    const packs = loadCuratedThemePacks();
    expect(packs.length).toBeGreaterThan(0);

    for (const pack of packs) {
      const bodyHex = pack.payloads.herdr.body;
      const selectionHex = pack.payloads.herdr.selection_bg;
      const groundHex = pack.payloads.herdr.ground;

      // The hard floor: never traded away, on any of the 26 — see
      // palette/selection.ts's resolveSelectionAndBody.
      expect(contrastRatio(bodyHex, selectionHex)).toBeGreaterThanOrEqual(TEXT_MIN_RATIO);
      // Recorded rather than hidden: every pack reaches at least a visible
      // highlight, even the 10 for which SELECTION_IDEAL_RATIO (2.0) is
      // mathematically unreachable alongside the hard floor above (see
      // CHM-30's own worked proof, e.g. tokyo-night-light's 4.52).
      expect(contrastRatio(selectionHex, groundHex)).toBeGreaterThanOrEqual(SELECTION_MIN_VISIBLE_RATIO);
    }
  });

  it("gives every pack whose ground carries meaningful chroma a selection that keeps some too, rather than collapsing to a hue-free grey (CHM-38)", () => {
    // The real 26 committed under themes/ — 25 of them shipped a selection
    // with essentially zero chroma before this fix, gruvbox-dark's own
    // untouched candidate being the one exception.
    const packs = loadCuratedThemePacks();
    expect(packs.length).toBeGreaterThan(0);

    for (const pack of packs) {
      const groundHex = pack.payloads.herdr.ground;
      const selectionHex = pack.payloads.herdr.selection_bg;
      if (chromaOf(groundHex) > SELECTION_MIN_CHROMA) {
        expect(chromaOf(selectionHex)).toBeGreaterThan(SELECTION_MIN_CHROMA);
      }
    }
  });

  it("never ships a pure black or pure white selection (CHM-38 fixture: Solarized Dark shipped #000000)", () => {
    const packs = loadCuratedThemePacks();
    expect(packs.length).toBeGreaterThan(0);

    for (const pack of packs) {
      expect(pack.payloads.herdr.selection_bg).not.toBe("#000000");
      expect(pack.payloads.herdr.selection_bg).not.toBe("#ffffff");
    }
  });

  it("repairs Solarized Dark's muted, which fails its floor before repair (fixture: 2.11)", () => {
    const scheme = readVendoredScheme("iTerm2 Solarized Dark.json");
    const pack = buildThemePack(scheme, "Solarized", ATTRIBUTION);

    const groundHex = pack.payloads["oh-my-posh"].ground;
    const mutedHex = pack.payloads["oh-my-posh"].muted;
    expect(contrastRatio(mutedHex, groundHex)).toBeGreaterThanOrEqual(MUTED_MIN_RATIO);
  });

  it("clears every text role's floor for every curated family — Gruvbox Dark's accent fails before repair (fixture: 3.48)", () => {
    const scheme = readVendoredScheme("Gruvbox Dark.json");
    const pack = buildThemePack(scheme, "Gruvbox", ATTRIBUTION);

    const groundHex = pack.payloads["oh-my-posh"].ground;
    for (const role of ["body", "accent", "success", "error"] as const) {
      const hex = pack.payloads["oh-my-posh"][role];
      expect(contrastRatio(hex, groundHex)).toBeGreaterThanOrEqual(TEXT_MIN_RATIO);
    }
  });

  it("omits attribution entirely when none is given — a user pack has no upstream to credit", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula");

    expect(pack.manifest.attribution).toBeUndefined();
    expect(Object.hasOwn(pack.manifest, "attribution")).toBe(false);
  });

  it("uses an explicit slug verbatim instead of deriving one from family and appearance", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", undefined, "catppuccin-dark");

    // "catppuccin-dark" is not what toSlug("Dracula", "dark") would produce
    // ("dracula-dark") — proving the explicit slug wins outright, not just
    // as a tiebreak.
    expect(pack.manifest.slug).toBe("catppuccin-dark");
  });

  it("still derives a slug from family and appearance when no explicit slug is given", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    expect(pack.manifest.slug).toBe("dracula-dark");
  });
});

describe("Windows Terminal's own foreground clears body-on-selection (CHM-33)", () => {
  // CHM-33: three bundled packs shipped Windows Terminal's own raw,
  // unrepaired `foreground` sitting behind the *resolved* `selectionBackground`
  // — unreadable underneath it (3.13/3.60/3.48 for body-on-selection, floor
  // 4.5) even though herdr's own copy of body, already nudged by
  // resolveSelectionAndBody, was fine all along. buildThemePack now wires
  // that same resolved body into this payload's `foreground` too, so the two
  // targets can never disagree about what body is, the same way they already
  // could not disagree about what selection is (CHM-30).
  it("clears body-on-selection for every one of the 26 bundled packs, measured the way the terminal itself paints it — foreground on selectionBackground", () => {
    const packs = loadCuratedThemePacks();
    expect(packs.length).toBe(26);

    for (const pack of packs) {
      const { foreground, selectionBackground } = pack.payloads["windows-terminal"];
      expect(contrastRatio(foreground, selectionBackground)).toBeGreaterThanOrEqual(TEXT_MIN_RATIO);
    }
  });

  // The three packs this ticket names by hand, asserted individually rather
  // than folded into the loop above, so a regression on any one of them
  // fails with its own slug and achieved ratio rather than a generic
  // "some pack failed" message. Achieved ratios are this fix's own output
  // (see tools/build-theme-packs.ts's describeBodyNudge), not invented.
  const NAMED_FIXTURES = [
    { slug: "solarized-light", achievedRatio: 4.73 },
    { slug: "everforest-light", achievedRatio: 4.74 },
    { slug: "tokyo-night-light", achievedRatio: 4.70 },
  ];

  it.each(NAMED_FIXTURES)(
    "clears body-on-selection for $slug, one of the three CHM-33 names by hand (fixture: shipped 3.13/3.60/3.48 before this fix)",
    ({ slug, achievedRatio }) => {
      const packs = loadCuratedThemePacks();
      const pack = packs.find((candidate) => candidate.manifest.slug === slug);
      if (!pack) throw new Error(`fixture pack not found: ${slug}`);

      const { foreground, selectionBackground } = pack.payloads["windows-terminal"];
      const ratio = contrastRatio(foreground, selectionBackground);
      expect(ratio).toBeGreaterThanOrEqual(TEXT_MIN_RATIO);
      expect(ratio).toBeCloseTo(achievedRatio, 1);
    },
  );

  /**
   * Every selection-vs-ground ratio a hue-free grey can reach while also
   * clearing `bodyFloorRatio` against `bodyHex`, sampled finely across the
   * whole luminance range rather than reasoned about analytically — a
   * brute-force check independent of selection.ts's own search, so this
   * proves the feasible band's shape instead of assuming the code under
   * test got it right (code-standards.md, "test behavior, not
   * implementation"). Restricting to grey is not a narrowing of the search:
   * contrastRatio is a function of luminance alone, so a tinted colour at
   * the same luminance reaches the exact same ratio (see
   * groundTintedAtLuminance's own doc comment).
   */
  function bestGroundRatioClearingBodyFloor(groundHex: string, bodyHex: string, bodyFloorRatio: number): number {
    const SAMPLE_COUNT = 2000;
    let best = 1;
    for (let sample = 0; sample <= SAMPLE_COUNT; sample += 1) {
      const candidateHex = fromHsl({ hue: 0, saturation: 0, lightness: (sample / SAMPLE_COUNT) * 100 });
      if (contrastRatio(candidateHex, bodyHex) < bodyFloorRatio) continue;
      best = Math.max(best, contrastRatio(candidateHex, groundHex));
    }
    return best;
  }

  it("computes everforest-light's feasible band against its own unrepaired body and shows it is empty at SELECTION_MIN_VISIBLE_RATIO — the one pack CHM-33 calls genuinely infeasible, not merely buggy", () => {
    // everforest-light's own raw scheme values (ground, foreground) — see
    // themes/everforest-light.json's history, before CHM-33's body nudge.
    const best = bestGroundRatioClearingBodyFloor("#efebd4", "#5c6a72", TEXT_MIN_RATIO);

    expect(best).toBeLessThan(SELECTION_MIN_VISIBLE_RATIO);
    expect(best).toBeCloseTo(1.2, 1);
  });

  it("computes solarized-light and tokyo-night-light as feasible against their own unrepaired body — ordinary bugs, not impossibilities, unlike everforest-light above", () => {
    // Both packs' own raw scheme values (ground, foreground).
    const solarizedBest = bestGroundRatioClearingBodyFloor("#fdf6e3", "#657b83", TEXT_MIN_RATIO);
    const tokyoNightBest = bestGroundRatioClearingBodyFloor("#e1e2e7", "#3760bf", TEXT_MIN_RATIO);

    expect(solarizedBest).toBeGreaterThanOrEqual(SELECTION_MIN_VISIBLE_RATIO);
    expect(tokyoNightBest).toBeGreaterThanOrEqual(SELECTION_MIN_VISIBLE_RATIO);
  });
});

describe("ANSI slot repair (CHM-32)", () => {
  it("clears ANSI_MIN_RATIO for every one of the 16 ANSI slots, in every bundled pack", () => {
    // The real 26 committed under themes/, generated by
    // tools/build-theme-packs.ts — not a re-derived copy — so this proves
    // what actually ships.
    const packs = loadCuratedThemePacks();
    expect(packs.length).toBeGreaterThan(0);

    for (const pack of packs) {
      const scheme = pack.payloads["windows-terminal"];
      for (const slotName of ANSI_SLOT_NAMES) {
        expect(contrastRatio(scheme[slotName], scheme.background)).toBeGreaterThanOrEqual(ANSI_MIN_RATIO);
      }
    }
  });

  // The four bundled packs CHM-32 names by hand: ANSI black shipped
  // byte-identical to the background (contrast 1.00) before this repair —
  // the "black circles in dark mode" bug, Claude Code's own bullet markers
  // drawn in ANSI black.
  const BLACK_AT_ONE_FIXTURES = [
    { slug: "gruvbox-dark", fileName: "Gruvbox Dark.json" },
    { slug: "gruvbox-light", fileName: "Gruvbox Light.json" },
    { slug: "monokai-dark", fileName: "Monokai Classic.json" },
    { slug: "night-owl-dark", fileName: "Night Owl.json" },
  ];

  it.each(BLACK_AT_ONE_FIXTURES)("repairs $slug's ANSI black, shipped byte-identical to its background before CHM-32 (fixture: 1.00)", ({ slug, fileName }) => {
    const originalScheme = readVendoredScheme(fileName);
    expect(contrastRatio(originalScheme.black, originalScheme.background)).toBeCloseTo(1, 2);

    const packs = loadCuratedThemePacks();
    const pack = packs.find((candidate) => candidate.manifest.slug === slug);
    if (!pack) throw new Error(`fixture pack not found: ${slug}`);

    const shippedBlack = pack.payloads["windows-terminal"].black;
    expect(shippedBlack).not.toBe(originalScheme.black);
    expect(contrastRatio(shippedBlack, pack.payloads["windows-terminal"].background)).toBeGreaterThanOrEqual(ANSI_MIN_RATIO);
  });
});

describe("parseThemePack", () => {
  it("round-trips a built pack through JSON", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const pack = buildThemePack(scheme, "Dracula", ATTRIBUTION);

    const roundTripped = parseThemePack(JSON.parse(JSON.stringify(pack)), "dracula-dark.json");
    expect(roundTripped).toEqual(pack);
  });

  it("names the file when a pack is malformed", () => {
    expect(() => parseThemePack({ manifest: {} }, "broken.json")).toThrow(/broken\.json/);
  });
});

describe("parseUserPackManifest", () => {
  it("parses a user manifest naming a scheme, a family and a declared slug", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const manifest = parseUserPackManifest({ slug: "my-dracula-dark", family: "My Dracula", scheme }, "my-dracula");

    expect(manifest.slug).toBe("my-dracula-dark");
    expect(manifest.family).toBe("My Dracula");
    expect(manifest.scheme).toEqual(scheme);
  });

  it("allows slug and family to both be omitted", () => {
    const scheme = readVendoredScheme("Dracula.json");
    const manifest = parseUserPackManifest({ scheme }, "my-dracula");

    expect(manifest.slug).toBeUndefined();
    expect(manifest.family).toBeUndefined();
  });

  it("names the pack directory when a user manifest is malformed", () => {
    expect(() => parseUserPackManifest({ family: "Broken" }, "broken-pack")).toThrow(/broken-pack/);
  });
});
