import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseThemePack, type ThemePack } from "./theme-pack.js";

const currentDir = path.dirname(fileURLToPath(import.meta.url));

/**
 * The curated packs generated by tools/build-theme-packs.ts and committed
 * under themes/ — the only theme data this package ships. Unlike
 * vendor/iterm2-color-schemes (build-time only, read by that tool and
 * never installed), themes/ is listed in package.json's "files" and exists
 * on every install.
 */
const THEME_PACK_DIR = path.join(currentDir, "..", "..", "themes");

/**
 * Reads every bundled pack from themes/. This is the one place src/palette/
 * touches the filesystem outside of tests — the packs are read-only,
 * shipped with the package, and never user-owned, the same exemption
 * loadVendoredSchemes held before it moved to build-time-only tooling (see
 * tools/vendor-scheme-library.ts). Nothing on this path reads vendor/.
 */
export function loadCuratedThemePacks(): ThemePack[] {
  const packFileNames = readdirSync(THEME_PACK_DIR).filter(
    (fileName) => fileName.endsWith(".json") && fileName !== "index.json",
  );

  return packFileNames.map((fileName) => {
    const rawJson: unknown = JSON.parse(readFileSync(path.join(THEME_PACK_DIR, fileName), "utf8"));
    return parseThemePack(rawJson, fileName);
  });
}
